name: Harbour 34 binaries DYN 32b MinGW 102

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    runs-on: windows-latest

    if: github.actor == github.event.repository.owner.login

    steps:
    - name: Checkout vszakats/hb harbour repo
      uses: actions/checkout@v2
      with:
       repository: vszakats/hb
       path: harbour

    - name: Install dependencies
      run: |
        (new-object System.Net.WebClient).DownloadFile('https://github.com/brechtsanders/winlibs_mingw/releases/download/10.2.0-11.0.0-9.0.0-r3/winlibs-i686-posix-dwarf-gcc-10.2.0-llvm-11.0.0-mingw-w64-8.0.0-r3.zip', 'C:\temp\mingw32.zip')
        Expand-Archive -LiteralPath C:\temp\mingw32.zip -DestinationPath C:\mingw32 -Force
         (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/hmg_tools_compilation/raw/main/bin/OpenSSL-Win32.zip', 'C:\temp\OpenSSL-Win32.zip')
        Expand-Archive -LiteralPath C:\temp\OpenSSL-Win32.zip -DestinationPath C:\OpenSSL -Force
         (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/hmg_tools_compilation/raw/main/bin/curl-7.54.0-win32-mingw.zip', 'C:\temp\curl-7.54.0-win32-mingw.zip')
        Expand-Archive -LiteralPath C:\temp\curl-7.54.0-win32-mingw.zip -DestinationPath C:\curl -Force
         (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/hmg_tools_compilation/raw/main/bin/acesdk.zip', 'C:\temp\acesdk.zip')
        Expand-Archive -LiteralPath C:\temp\acesdk.zip -DestinationPath C:\acesdk -Force
         (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/ighoo/raw/master/workflow/win-make.zip', 'C:\temp\win-make.zip')
        Expand-Archive -LiteralPath C:\temp\win-make.zip -DestinationPath C:\win-make -Force

#        (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/mingw32.zip', 'C:\temp\mingw32.zip')
#        Expand-Archive -LiteralPath C:\temp\mingw32.zip -DestinationPath C:\mingw32 -Force
#         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/OpenSSL-Win32.zip', 'C:\temp\OpenSSL-Win32.zip')
#        Expand-Archive -LiteralPath C:\temp\OpenSSL-Win32.zip -DestinationPath C:\OpenSSL -Force
#         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/curl-7.54.0-win32-mingw.zip', 'C:\temp\curl-7.54.0-win32-mingw.zip')
#        Expand-Archive -LiteralPath C:\temp\curl-7.54.0-win32-mingw.zip -DestinationPath C:\curl -Force
#         (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/acesdk.zip', 'C:\temp\acesdk.zip')
#        Expand-Archive -LiteralPath C:\temp\acesdk.zip -DestinationPath C:\acesdk -Force

    - name: Compile Harbour
      shell: cmd
      run: |
        cd harbour
        set HB_BUILD_MODE=c
        set HB_USER_PRGFLAGS=-l-
        set HB_BUILD_PARTS=all
        set HB_BUILD_CONTRIBS=
        set HB_WITH_OPENSSL=c:\openssl\include
        set HB_WITH_CURL=c:\curl\include
        set HB_WITH_ADS=c:\acesdk
        set HB_STATIC_OPENSSL=yes
        set HB_STATIC_CURL=yes
        set HB_COMPILER=mingw
        set HB_BUILD_CONTRIB_DYN=yes
        set HB_BUILD_DYN=yes
        set HB_WITH_LIBHARU=c:\harbour\contrib\hbhpdf
        set path=c:\mingw32\mingw32\bin;c:\openssl\bin;c:\curl;C:\win-make;%path%
        win-make.exe

    - name: Create output folders
      shell: cmd
      run: |
        mkdir output

        robocopy harbour\ output /E
        if %ERRORLEVEL% EQU 1 set ERRORLEVEL=0
        echo %ERRORLEVEL%
        echo creating harbour binaries ErrorLevel = %ERRORLEVEL%

        IF EXIST output\.git rmdir output\.git /S /Q
        del output\.git* /S /Q

        echo limpiar objects 0
        IF EXIST output\os2-make.exe del output\os2-make.exe /S /Q
        IF EXIST output\dos-make.exe del output\dos-make.exe /S /Q
        IF EXIST output\win-make.exe del output\win-make.exe /S /Q
        IF EXIST output\.travis.yml del output\.travis.yml /S /Q

        IF EXIST output\package rmdir output\package /S /Q
        IF EXIST output\debian rmdir output\debian /S /Q
        IF EXIST output\config rmdir output\config /S /Q
        IF EXIST output\addons rmdir output\addons /S /Q
        IF EXIST output\lib\win\mingw\.hbmk rmdir output\lib\win\mingw\.hbmk /S /Q

        move output\bin\win\mingw\*.* output\bin
        IF EXIST output\bin\win rmdir output\bin\win /S /Q
        echo mover harbour binaries ErrorLevel = %ERRORLEVEL%

        IF EXIST output\src\rtl\gtwin\obj rmdir output\src\rtl\gtwin\obj /S /Q
        IF EXIST output\src\rtl\gtstd\obj rmdir output\src\rtl\gtstd\obj /S /Q
        IF EXIST output\src\rtl\gtstd\obj rmdir output\src\rtl\gtstd\obj /S /Q
        IF EXIST output\src\rdd\usrrdd\rdds\obj rmdir output\src\rdd\usrrdd\rdds\obj /S /Q

        move output\lib\3rd\win\mingw\libunicow*.* output\lib\win\mingw
        IF EXIST output\lib\3rd rmdir output\lib\3rd /S /Q
        IF EXIST output\src\vm\obj rmdir output\src\vm\obj /S /Q
        IF EXIST output\src\rtl\obj rmdir output\src\rtl\obj /S /Q
        IF EXIST output\src\rdd\obj rmdir output\src\rdd\obj /S /Q
        IF EXIST output\src\pp\obj rmdir output\src\pp\obj /S /Q
        IF EXIST output\src\nortl\obj rmdir output\src\nortl\obj /S /Q
        IF EXIST output\src\main\obj rmdir output\src\main\obj /S /Q
        IF EXIST output\src\macro\obj rmdir output\src\macro\obj /S /Q
        IF EXIST output\src\lang\obj rmdir output\src\lang\obj /S /Q
        IF EXIST output\src\hbextern\obj rmdir output\src\hbextern\obj /S /Q
        IF EXIST output\src\dynlib\obj rmdir output\src\dynlib\obj /S /Q
        IF EXIST output\src\debug\obj rmdir output\src\debug\obj /S /Q
        IF EXIST output\src\compiler\obj rmdir output\src\compiler\obj /S /Q
        IF EXIST output\src\common\obj rmdir output\src\common\obj /S /Q
        IF EXIST output\src\codepage\obj rmdir output\src\codepage\obj /S /Q
        IF EXIST output\src\3rd\zlib\obj rmdir output\src\3rd\zlib\obj /S /Q
        IF EXIST output\src\3rd\tiff\obj rmdir output\src\3rd\tiff\obj /S /Q
        IF EXIST output\src\3rd\png\obj rmdir output\src\3rd\png\obj /S /Q
        IF EXIST output\src\3rd\pcre\obj rmdir output\src\3rd\pcre\obj /S /Q
        IF EXIST output\src\3rd\jpeg\obj rmdir output\src\3rd\jpeg\obj /S /Q
        IF EXIST output\src\rdd\usrrdd\obj rmdir output\src\rdd\usrrdd\obj /S /Q
        IF EXIST output\src\rdd\nulsys\obj rmdir output\src\rdd\nulsys\obj /S /Q
        IF EXIST output\src\rdd\hsx\obj rmdir output\src\rdd\hsx\obj /S /Q
        IF EXIST output\src\rdd\hbsix\obj rmdir output\src\rdd\hbsix\obj /S /Q
        IF EXIST output\src\rdd\dbfntx\obj rmdir output\src\rdd\dbfntx\obj /S /Q
        IF EXIST output\src\rdd\dbfnsx\obj rmdir output\src\rdd\dbfnsx\obj /S /Q
        IF EXIST output\src\rdd\dbffpt\obj rmdir output\src\rdd\dbffpt\obj /S /Q
        IF EXIST output\src\rdd\dbfcdx\obj rmdir output\src\rdd\dbfcdx\obj /S /Q
        IF EXIST output\src\vm\vmmt\obj rmdir output\src\vm\vmmt\obj /S /Q
        IF EXIST output\src\vm\mainwin\obj rmdir output\src\vm\mainwin\obj /S /Q
        IF EXIST output\src\vm\mainstd\obj rmdir output\src\vm\mainstd\obj /S /Q
        IF EXIST output\src\vm\maindllp\obj rmdir output\src\vm\maindllp\obj /S /Q
        IF EXIST output\src\vm\maindllh\obj rmdir output\src\vm\maindllh\obj /S /Q
        IF EXIST output\utils\hbtest\obj rmdir output\utils\hbtest\obj /S /Q
        IF EXIST output\utils\hbmk2\obj rmdir output\utils\hbmk2\obj /S /Q
        IF EXIST output\utils\hbi18n\obj rmdir output\utils\hbi18n\obj /S /Q

        echo fin limpiar objects

        if %ERRORLEVEL% EQU 1 set ERRORLEVEL=0

    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYYMMDD-HH

    - name: Upload Harbour to artifact
      env:
         F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: hb34_dyn_mgw102_32b_${{ env.F_TIME }}
       path: output
