name: HMG official all libs 32bit MinGW 930 unicode

on:
    push:

jobs:
  build:
    runs-on: windows-latest

    if: github.actor == github.event.repository.owner.login

    steps:
    - name: Checkout asistex repo
      uses: actions/checkout@v2
      with:
       repository: asistex/HMG
       path: asistex/HMG

    - name: Install dependencies
      run: |
        (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/mingw32.zip', 'C:\temp\mingw32.zip')
        Expand-Archive -LiteralPath C:\temp\mingw32.zip -DestinationPath C:\mingw32 -Force
        (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/HMG/raw/master/workflows/hb32_mgw930_32b_2020_10_27.zip', 'C:\temp\harbour.zip')
        Expand-Archive -LiteralPath C:\temp\harbour.zip -DestinationPath C:\harbour -Force
        gcc --version
        C:\harbour\bin\harbour -build

    - name: Building lib HMG
      shell: cmd
      run: |
        cd asistex\hmg
        set path=c:\mingw32\mingw32\bin;c:\harbour\bin;%path%
        BuildAllLib32.bat
        echo creating hmg libraries ErrorLevel = %ERRORLEVEL%

    - name: Create output folders...
      shell: cmd
      run: |
        mkdir output

        robocopy c:\harbour output\harbour /E
        if %ERRORLEVEL% EQU 1 set ERRORLEVEL=0
        echo %ERRORLEVEL%
        echo creating harbour binaries ErrorLevel = %ERRORLEVEL%

        mkdir output\source
        mkdir output\include
        mkdir output\lib
        mkdir output\doc
        mkdir output\samples
        mkdir output\resources
        mkdir output\hfcl
        echo creating output folders ErrorLevel = %ERRORLEVEL%

        move asistex\hmg\source\*.* output\source
        echo creating output\source ErrorLevel = %ERRORLEVEL%
        move asistex\hmg\include\*.* output\include
        echo creating output\include ErrorLevel = %ERRORLEVEL%
        move asistex\hmg\lib\*.* output\lib
        echo creating output\lib ErrorLevel = %ERRORLEVEL%
        move asistex\hmg\doc\*.* output\doc
        echo creating output\doc ErrorLevel = %ERRORLEVEL%
        move asistex\hmg\samples\*.* output\samples
        echo creating output\samples ErrorLevel = %ERRORLEVEL%
        move asistex\hmg\resources\*.* output\resources
        echo creating output\resources ErrorLevel = %ERRORLEVEL%
        move asistex\hmg\hfcl\*.* output\hfcl
        echo creating output\hfcl ErrorLevel = %ERRORLEVEL%

        copy asistex\hmg\*.* output\

    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD

    - name: Create artifact
      env:
        TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
        name: hmgoffi_all_hb32_mgw930_uni_32b_${{ env.TIME }}
        path: output

