name: HMG official all libs 32bit MinGW 930 unicode

on:
    push:

jobs:
  build:
    runs-on: windows-latest

    if: github.actor == github.event.repository.owner.login

    steps:
    - name: Checkout HMG-Official repo
      uses: actions/checkout@v2
      with:
       repository: HMG-Official/HMG
       path: HMG-Official/HMG

    - name: Install dependencies
      run: |
        (new-object System.Net.WebClient).DownloadFile('https://bitbucket.org/lorenzodla/mod_harbour_actions_resources/downloads/mingw32.zip', 'C:\temp\mingw32.zip')
        Expand-Archive -LiteralPath C:\temp\mingw32.zip -DestinationPath C:\mingw32 -Force
        (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/HMG/raw/master/workflows/hb32_mgw930_32b_2020_10_27.zip', 'C:\temp\harbour.zip')
        Expand-Archive -LiteralPath C:\temp\harbour.zip -DestinationPath C:\harbour -Force
        gcc --version

    - name: Building lib HMG
      shell: cmd
      run: |
        cd HMG-Official\hmg
        set path=c:\mingw32\mingw32\bin;c:\harbour\bin;%path%
        BuildAllLib32.bat

    - name: Create output folders...
      shell: cmd
      run: |
        mkdir output

        mkdir output\harbour\bin
        mkdir output\harbour\contrib
        mkdir output\harbour\doc
        mkdir output\harbour\include
        mkdir output\harbour\lib

        move harbour\bin\*.* output\harbour\bin
        move harbour\contrib\*.* output\harbour\contrib
        move harbour\doc\*.* output\harbour\doc
        move harbour\include\*.* output\harbour\include
        move harbour\lib\*.* output\harbour\lib

        mkdir output\source
        mkdir output\include
        mkdir output\lib
        mkdir output\contrib
        mkdir output\doc
        mkdir output\samples
        mkdir output\resources
        mkdir output\hfsl
        mkdir output\lib

        move HMG-Official\source\*.* output\source
        move HMG-Official\include\*.* output\include
        move HMG-Official\lib\*.* output\lib
        move HMG-Official\contrib\*.* output\contrib
        move HMG-Official\doc\*.* output\doc
        move HMG-Official\samples\*.* output\samples
        move HMG-Official\resources\*.* output\resources
        move HMG-Official\hfsl\*.* output\hfsl
        move HMG-Official\lib\*.* output\lib

        copy HMG-Official\hmg\*.* output\

    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD

    - name: Create artifact
      env:
        TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
        name: hmgoffi_all_hb32_mgw930_uni_32b_${{ env.TIME }}
        path: output

