name: test github

on:
    push:

jobs:
  build:
    runs-on: windows-latest
    
    if: github.actor == github.event.repository.owner.login
    
    steps:    
    - name: Checkout ighoo repo
      uses: actions/checkout@v2
      with:
       repository: asistex/ighoo
       path: asistex/ighoo

    - name: Install dependencies
      run: |
        (new-object System.Net.WebClient).DownloadFile('https://github.com/asistex/ighoo/raw/master/bin/test.zip', 'C:\temp\test.zip')
        Expand-Archive -LiteralPath c:\temp\test.zip -DestinationPath c:\test -Force         
         
    - name: Compile test
      shell: cmd
      run: |
        dir c:\test
        
    - name: Create output folders
      shell: cmd
      run: |
        mkdir output
        robocopy c:\test output /E /V /X /FP
        set ERRORLEVEL=0

        :: mkdir output\tests
        :: copy c:\test\tests output\tests /E

    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY_MM_DD
 
    - name: Upload test to artifact
      env:
         TIME: "${{ steps.current-time.outputs.formattedTime }}"
      uses: actions/upload-artifact@v2
      with:
       name: test_${{ env.TIME }}
       path: output

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Required
        commit_message: Apply automatic changes
    
        # Optional branch to push to, defaults to the current branch
        branch: ighoo
    
        # Optional options appended to `git-commit`
        # See https://git-scm.com/docs/git-commit for a list of available options
        commit_options: '--no-verify --signoff'
    
        # Optional glob pattern of files which should be added to the commit
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: test_${{ env.TIME }} bin
    
        # Optional local file path to the repository
        # repository: .
    
        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot
        commit_user_email: my-github-actions-bot@example.org
        commit_author: Author <actions@github.com>
    
        # Optional tag message 
        # Action will create and push a new tag to the remote repository and the defined branch
        tagging_message: 'v1.0.0'
    
        # Optional options appended to `git-push`
        # See git-push documentation for details: https://git-scm.com/docs/git-push#_options
        push_options: '--force'
        
        # Optional: Disable dirty check and always try to create a commit and push
        skip_dirty_check: true